# this Massage example shows a few simple messages you might want to send.

name = "simple" # this will be the name of your structures
description = "a simple communication protocol"

[commands.hello]
id = 1 # unique command identifier
description = "say hello!"

[[commands.hello.arguments]]
format = "String" # may be String, U8, U16, U32, U64, I8, I16, I32, I64, F32, F64
name = "name" # unique argument identifier
description = "your name"

[commands.goodbye]
id = 2
description = "say goodbye..."
